services:
  - type: web
    name: claudeproxy
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: BROWSER
        value: chromium
      - key: SERVER_ONLY
        value: "1"
      - key: RUNNING_IN_DOCKER
        value: "1"
